[versions]
minecraft = "1.21.1"
parchment = "2024.11.17"
# Dependencies
neoforge = "21.1.213"
fabric-loader = "0.17.2"
kubejs = "2101.7.2-build.348"
neoforge-tacz = "7374584"
neoforge-playeranimator = "4587214"
jei = "19.25.1.334"
mixinextras = "0.4.1"

commons-math3 = "3.6.1"
luaj = "3.0.8-figura"

[plugins]
architectury = { id = "architectury-plugin", version = "3.4-SNAPSHOT" }
loom = { id = "dev.architectury.loom", version = "1.11-SNAPSHOT" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }

[libraries]
commons-math3 = { module = "org.apache.commons:commons-math3", version.ref = "commons-math3" }
luaj-core = { module = "com.github.FiguraMC.luaj:luaj-core", version.ref = "luaj" }
luaj-jse = { module = "com.github.FiguraMC.luaj:luaj-jse", version.ref = "luaj" }
mixinextras = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinextras" }
## NeoForge
neoforge-neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }
neoforge-mixinextras = { module = "io.github.llamalad7:mixinextras-neoforge", version.ref = "mixinextras" }
neoforge-tacz = { module = "curse.maven:tacz-1-21-1-1353462", version.ref = "neoforge-tacz" }
neoforge-kubejs = { module = "dev.latvian.mods:kubejs-neoforge", version.ref = "kubejs" }
neoforge-jei = { module = "mezz.jei:jei-1.21.1-neoforge", version.ref = "jei" }
neoforge-playeranimator = { module = "curse.maven:playeranimator-658587", version.ref = "neoforge-playeranimator" }
## Fabric
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
